# ---------- model wiring ----------
name: recursive_reasoning.TRM_RTify@TRM_Rtify
forward_dtype: bfloat16


# ---------- backbone ----------
hidden_size: 512
num_heads: 8
expansion: 4
dropout: 0.1
n_layers: 1

# ---------- recursion ----------
S_steps: 1           
R_steps: 1   

# ---------- recursion ----------
scale_input_injection: True
state_scale_init: 0.1  

pos_encodings: rope
rope_theta: 10000.0

# ------------- RTify -------------
halt_max_steps: 16
halt_warmup_steps: 1000 
theta_init: 5
train_theta: True        
detach_fw_input: False     
train_fixed_steps: False 
fw_hidden_mult: 1.0  
lambda_halt: 1e-5 
lambda_ready: 0.1